version: '2'
services:
  datacube-wms:
    image: geoscienceaustralia/datacube-wms:latest
    ports: 
      - 80
    env_file:
      - datacube.config
    environment:
      - PUBLIC_URL
      - VERSION
    volumes:
      - /opt/data:/opt/data
