version: '2'
services:
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - datacube.config
    volumes:
      - datacube_data:/opt/data
  datacube-jupyter:
    image: geoscienceaustralia/datacube-jupyter:latest
    ports: 
      - 80:80
    env_file:
      - datacube.config
    volumes:
      - datacube_data:/opt/data
    links:
      - "postgres"
volumes:
  datacube_data:
