version: '2'
services:
  postgres:
    image: postgres
    ports: 
      - 5432
    env_file:
      - datacube_local.config
  datacube-wms:
    image: geoscienceaustralia/datacube-wms:latest
    ports: 
      - 80:80
    env_file:
      - datacube_local.config
    environment:
      - PUBLIC_URL
    volumes:
      - /opt/data:/opt/data
    links:
      - postgres:postgres
  datacube-wms-bootstrap:
    image: geoscienceaustralia/datacube-wms-bootstrap:latest
    env_file:
      - datacube.config
    volumes:
      - /opt/data:/opt/data
    links:
      - postgres:postgres
